### ISSUE TITLE
Readme content

### ISSUE THREAD

**Issue by aikaterna** [Weirdo914/CRZA-eSports-cogs#1]
All the cogs listed here do not "belong to you", you should adhere to the licensing attached to each repo you took these cogs from and reinstate the credit you stripped from the info.jsons. Not only have you copied some of my work, there is unattributed work here from the Red project itself, Redjumpman, Flapjack, Will, Palm, Stevy, Caleb, and I'm sure other Red cog authors I haven't mentioned also have cogs in the list on your repo. Shame on you.

**Comment by Weirdo914** [comment]
You should mind your buisness and these cogs have been edited you fuckin idiot

**Comment by Bakersbakebread** [comment]
[https://giphy.com/gifs/reactionseditor-sassy-sass-l0IymiszgmwwfB5K0](url)

**Comment by CRZA5** [comment]
He doesn't even list to me (Owner of crzaesports) then how will he listen to you!
